language: java
jdk:
  - oraclejdk8
install: true

script:
  - ./gradlew clean build sonarqube -x test
  
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
