# Create the imageinspector webservice.
#
# You'll want to change the path to your shared directory (search for "hostPath").
#
apiVersion: v1
kind: Service
metadata:
  name: hub-imageinspector-ws-alpine
  namespace: hub-imageinspector-ws
  labels:
    app: hub-imageinspector-ws-alpine
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hub-imageinspector-ws-alpine
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-imageinspector-ws-alpine
  namespace: hub-imageinspector-ws
  labels:
    app: hub-imageinspector-ws-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-imageinspector-ws-alpine
  template:
    metadata:
      labels:
        app: hub-imageinspector-ws-alpine
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: hub-imageinspector-ws-alpine
        image: blackducksoftware/hub-imageinspector-ws-alpine:2.2.0-SNAPSHOT
        command: ["java"]
        args: ["-jar", "/opt/blackduck/hub-imageinspector-ws/hub-imageinspector-ws.jar", "--server.port=8080", "--current.linux.distro=alpine", "--inspector.url.alpine=http://hub-imageinspector-ws-alpine.hub-imageinspector-ws", "--inspector.url.centos=http://hub-imageinspector-ws-centos.hub-imageinspector-ws", "--inspector.url.ubuntu=http://hub-imageinspector-ws-ubuntu.hub-imageinspector-ws"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: /your/dir/shared
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: hub-imageinspector-ws-centos
  namespace: hub-imageinspector-ws
  labels:
    app: hub-imageinspector-ws-centos
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: hub-imageinspector-ws-centos
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-imageinspector-ws-centos
  namespace: hub-imageinspector-ws
  labels:
    app: hub-imageinspector-ws-centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-imageinspector-ws-centos
  template:
    metadata:
      labels:
        app: hub-imageinspector-ws-centos
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: hub-imageinspector-ws-centos
        image: blackducksoftware/hub-imageinspector-ws-centos:2.2.0-SNAPSHOT
        command: ["java"]
        args: ["-jar", "/opt/blackduck/hub-imageinspector-ws/hub-imageinspector-ws.jar", "--server.port=8081", "--current.linux.distro=centos", "--inspector.url.alpine=http://hub-imageinspector-ws-alpine.hub-imageinspector-ws", "--inspector.url.centos=http://hub-imageinspector-ws-centos.hub-imageinspector-ws", "--inspector.url.ubuntu=http://hub-imageinspector-ws-ubuntu.hub-imageinspector-ws"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: /your/dir/shared
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: hub-imageinspector-ws-ubuntu
  namespace: hub-imageinspector-ws
  labels:
    app: hub-imageinspector-ws-ubuntu
spec:
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: hub-imageinspector-ws-ubuntu
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-imageinspector-ws-ubuntu
  namespace: hub-imageinspector-ws
  labels:
    app: hub-imageinspector-ws-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-imageinspector-ws-ubuntu
  template:
    metadata:
      labels:
        app: hub-imageinspector-ws-ubuntu
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: hub-imageinspector-ws-ubuntu
        image: blackducksoftware/hub-imageinspector-ws-ubuntu:2.2.0-SNAPSHOT
        command: ["java"]
        args: ["-jar", "/opt/blackduck/hub-imageinspector-ws/hub-imageinspector-ws.jar", "--server.port=8082", "--current.linux.distro=ubuntu", "--inspector.url.alpine=http://hub-imageinspector-ws-alpine.hub-imageinspector-ws", "--inspector.url.centos=http://hub-imageinspector-ws-centos.hub-imageinspector-ws", "--inspector.url.ubuntu=http://hub-imageinspector-ws-ubuntu.hub-imageinspector-ws"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: /your/dir/shared
          type: Directory
