# Create the imageinspector webservice.
#
# You'll want to change the path to your shared directory in 3 places (search for "hostPath").
#
apiVersion: v1
kind: Service
metadata:
  name: blackduck-imageinspector-alpine
  namespace: blackduck-imageinspector
  labels:
    app: blackduck-imageinspector-alpine
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: blackduck-imageinspector-alpine
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackduck-imageinspector-alpine
  namespace: blackduck-imageinspector
  labels:
    app: blackduck-imageinspector-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackduck-imageinspector-alpine
  template:
    metadata:
      labels:
        app: blackduck-imageinspector-alpine
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: blackduck-imageinspector-alpine
        image: blackducksoftware/blackduck-imageinspector-alpine:3.0.0
        command: ["java"]
        args: ["-jar", "/opt/blackduck/blackduck-imageinspector/blackduck-imageinspector.jar", "--server.port=8080", "--current.linux.distro=alpine", "--inspector.url.alpine=http://blackduck-imageinspector-alpine.blackduck-imageinspector", "--inspector.url.centos=http://blackduck-imageinspector-centos.blackduck-imageinspector", "--inspector.url.ubuntu=http://blackduck-imageinspector-ubuntu.blackduck-imageinspector"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: /your/dir/shared
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: blackduck-imageinspector-centos
  namespace: blackduck-imageinspector
  labels:
    app: blackduck-imageinspector-centos
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: blackduck-imageinspector-centos
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackduck-imageinspector-centos
  namespace: blackduck-imageinspector
  labels:
    app: blackduck-imageinspector-centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackduck-imageinspector-centos
  template:
    metadata:
      labels:
        app: blackduck-imageinspector-centos
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: blackduck-imageinspector-centos
        image: blackducksoftware/blackduck-imageinspector-centos:3.0.0
        command: ["java"]
        args: ["-jar", "/opt/blackduck/blackduck-imageinspector/blackduck-imageinspector.jar", "--server.port=8081", "--current.linux.distro=centos", "--inspector.url.alpine=http://blackduck-imageinspector-alpine.blackduck-imageinspector", "--inspector.url.centos=http://blackduck-imageinspector-centos.blackduck-imageinspector", "--inspector.url.ubuntu=http://blackduck-imageinspector-ubuntu.blackduck-imageinspector"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: /your/dir/shared
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: blackduck-imageinspector-ubuntu
  namespace: blackduck-imageinspector
  labels:
    app: blackduck-imageinspector-ubuntu
spec:
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: blackduck-imageinspector-ubuntu
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackduck-imageinspector-ubuntu
  namespace: blackduck-imageinspector
  labels:
    app: blackduck-imageinspector-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackduck-imageinspector-ubuntu
  template:
    metadata:
      labels:
        app: blackduck-imageinspector-ubuntu
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: blackduck-imageinspector-ubuntu
        image: blackducksoftware/blackduck-imageinspector-ubuntu:3.0.0
        command: ["java"]
        args: ["-jar", "/opt/blackduck/blackduck-imageinspector/blackduck-imageinspector.jar", "--server.port=8082", "--current.linux.distro=ubuntu", "--inspector.url.alpine=http://blackduck-imageinspector-alpine.blackduck-imageinspector", "--inspector.url.centos=http://blackduck-imageinspector-centos.blackduck-imageinspector", "--inspector.url.ubuntu=http://blackduck-imageinspector-ubuntu.blackduck-imageinspector"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: /your/dir/shared
          type: Directory
