# Docker Inspector generates markdown from the source code using the gradle task 'docs'.
# The task uses freemarker ftl files inside 'templates' and the files inside 'static' to create files fed to mkdocs.
# The generated markdown is placed inside 'generated' and 'mkdocs build' is run against that markdown and creates a 'site' directory.
# Neither the 'generated' folder nor the mkdocs 'site' folder should be added to source control.
# After running the 'docs' task, the 'site' folder can be uploaded to gh-pages.
# To build, install pip and python, then execute:
#   pip install mkdocs
#   pip install mkdocs-material
# To view the docs, you must execute:
#   At project root: gradlew docs
#   At docs/site: mkdocs serve
site_name: Black Duck Docker Inspector
theme:
  name: 'material'
docs_dir: 'generated'
nav:
     - <b>Documentation</b>: index.md
     - Overview: overview.md
     - Architecture: architecture.md
     - Properties: properties.md
     - Advanced: advanced.md
     - Deploying: deployment.md
     - Troubleshooting: troubleshooting.md
     - Release notes: releasenotes.md
